### ISSUE TITLE
Description link

### ISSUE THREAD

**Issue by seeren** [laurentfonquerne/laurentfonquerne-web#1]
There is no link for online visualisation !

**Comment by laurentfonquerne** [comment]
I'm trying to fix this.  But We were very busy with the java part. Very. Almost traumatized

**Comment by seeren** [comment]
Sory you close but there is still no link for online visualisation

**Comment by laurentfonquerne** [comment]
backlog

2017-09-04 15:37 GMT+02:00 Cyril Ichti <notifications@github.com>:
